path_classifiers:
  test:
    - exclude: profile_default
    - exclude: profile_bluesky/startup/archive
extraction:
  python:
    python_setup:
      version: 3
queries:
  - exclude: py/unused-import
  - exclude: py/polluting-import
